name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Archive Code
      run: |
        tar --exclude='.git' --exclude='node_modules' -czf app.tar.gz .

    - name: Upload Code to EC2
      run: |
        scp -i ~/.ssh/id_rsa app.tar.gz ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/

    - name: Extract and Restart App on EC2
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu
          rm -rf mensfashions_backend
          mkdir -p mensfashions_backend
          tar -xzf app.tar.gz -C mensfashions_backend
          rm app.tar.gz
          cd mensfashions_backend
          npm ci
          pm2 describe mensfashions > /dev/null
          if [ $? -eq 0 ]; then
            pm2 restart mensfashions
          else
            pm2 start server.js --name mensfashions
          fi
        EOF
